// 3D model sources (RUBRIC v2.2 licensing): every asset is CC0, listed in the page's Sources panel and CREDITS-3D.md.
export const MODEL_SOURCES: ReadonlyArray<{ name: string; kind: string; by: string; url: string; lic: string }> = [
  { name: 'Wood Floor', kind: 'texture', by: 'Dimitrios Savva', url: 'https://polyhaven.com/a/wood_floor', lic: 'CC0' },
  { name: 'Painted Plaster Wall', kind: 'texture', by: 'Amal Kumar', url: 'https://polyhaven.com/a/painted_plaster_wall', lic: 'CC0' },
  { name: 'Poly Wool Herringbone', kind: 'texture', by: 'colormass, Rico Cilliers', url: 'https://polyhaven.com/a/poly_wool_herringbone', lic: 'CC0' },
  { name: 'Cotton Jersey', kind: 'texture', by: 'colormass, Rico Cilliers', url: 'https://polyhaven.com/a/cotton_jersey', lic: 'CC0' },
  { name: 'Rough Linen', kind: 'texture', by: 'colormass, Rico Cilliers', url: 'https://polyhaven.com/a/rough_linen', lic: 'CC0' },
  { name: 'Grey Roof 01', kind: 'texture', by: 'Rob Tuytel', url: 'https://polyhaven.com/a/grey_roof_01', lic: 'CC0' },
  { name: 'Weathered Plank Siding', kind: 'texture', by: 'Dimitrios Savva', url: 'https://polyhaven.com/a/weathered_plank_siding', lic: 'CC0' },
  { name: 'Red Brick 03', kind: 'texture', by: 'Rob Tuytel', url: 'https://polyhaven.com/a/red_brick_03', lic: 'CC0' },
  { name: 'Concrete Floor 02', kind: 'texture', by: 'Rob Tuytel', url: 'https://polyhaven.com/a/concrete_floor_02', lic: 'CC0' },
  { name: 'Leafy Grass', kind: 'texture', by: 'Charlotte Baglioni', url: 'https://polyhaven.com/a/leafy_grass', lic: 'CC0' },
  { name: 'Black Walnut Veneer 01', kind: 'texture', by: 'Jenelle van Heerden', url: 'https://polyhaven.com/a/black_walnut_veneer_01', lic: 'CC0' },
  { name: 'Oak Veneer 01', kind: 'texture', by: 'Jenelle van Heerden', url: 'https://polyhaven.com/a/oak_veneer_01', lic: 'CC0' },
  { name: 'Wood Floor Deck', kind: 'texture', by: 'Dimitrios Savva', url: 'https://polyhaven.com/a/wood_floor_deck', lic: 'CC0' },
  { name: 'Tiles 038', kind: 'texture', by: 'Lennart Demes (ambientCG)', url: 'https://ambientcg.com/view?id=Tiles038', lic: 'CC0' },
  { name: 'Kloofendal 48d Partly Cloudy (Pure Sky)', kind: 'HDRI', by: 'Greg Zaal, Jarod Guest', url: 'https://polyhaven.com/a/kloofendal_48d_partly_cloudy_puresky', lic: 'CC0' },
  { name: 'Modern Arm Chair 01', kind: 'model', by: 'Vibrant Nordic', url: 'https://polyhaven.com/a/modern_arm_chair_01', lic: 'CC0' },
  { name: 'Ottoman 01', kind: 'model', by: 'Caspian Fortune', url: 'https://polyhaven.com/a/Ottoman_01', lic: 'CC0' },
  { name: 'Wooden Table 01', kind: 'model', by: 'Ethan Place', url: 'https://polyhaven.com/a/WoodenTable_01', lic: 'CC0' },
  { name: 'Throw Pillows 01', kind: 'model', by: 'Serhii Khromov', url: 'https://polyhaven.com/a/throw_pillows_01', lic: 'CC0' },
  { name: 'Potted Plant 04', kind: 'model', by: 'James Ray Cock', url: 'https://polyhaven.com/a/potted_plant_04', lic: 'CC0' },
  { name: 'Potted Plant 02', kind: 'model', by: 'Rico Cilliers', url: 'https://polyhaven.com/a/potted_plant_02', lic: 'CC0' },
  { name: 'Classic Nightstand 01', kind: 'model', by: 'Kirill Sannikov', url: 'https://polyhaven.com/a/ClassicNightstand_01', lic: 'CC0' },
  { name: 'three.js basis transcoder, Draco decoder', kind: 'runtime', by: 'three.js authors, Google', url: 'https://github.com/mrdoob/three.js', lic: 'MIT / Apache-2.0' },
];
